src/Entity/Batiment.php
<?php

namespace App\Entity;

use App\Repository\BatimentRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: BatimentRepository::class)]
class Batiment
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 20)]
    private ?string $nom = null;

    /**
     * @var Collection<int, Appartement>
     */
    #[ORM\OneToMany(targetEntity: Appartement::class, mappedBy: 'batiment')]
    private Collection $appartements;

    #[ORM\ManyToOne(inversedBy: 'batiments')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Syndic $syndic = null;

    public function __construct()
    {
        $this->appartements = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    /**
     * @return Collection<int, Appartement>
     */
    public function getAppartements(): Collection
    {
        return $this->appartements;
    }

    public function addAppartement(Appartement $appartement): static
    {
        if (!$this->appartements->contains($appartement)) {
            $this->appartements->add($appartement);
            $appartement->setBatiment($this);
        }

        return $this;
    }

    public function removeAppartement(Appartement $appartement): static
    {
        if ($this->appartements->removeElement($appartement)) {
            // set the owning side to null (unless already changed)
            if ($appartement->getBatiment() === $this) {
                $appartement->setBatiment(null);
            }
        }

        return $this;
    }

    public function getSyndic(): ?Syndic
    {
        return $this->syndic;
    }

    public function setSyndic(?Syndic $syndic): static
    {
        $this->syndic = $syndic;

        return $this;
    }

    public function getOccupedAppartements(): array
    {
        return $this->appartements->filter(function (Appartement $a) {
            $lasProprietaire = $a->getLastProprietaire();
            return $lasProprietaire && !$lasProprietaire->isSystem();
        })->map(function (Appartement $a) {
            return ['value' => $a->getId(), 'text' => $a->getAbsoluteName(false)];
        })->toArray();
    }
}

src/Entity/Proprietaire.php
<?php

namespace App\Entity;

use App\Repository\ProprietaireRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProprietaireRepository::class)]
class Proprietaire
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 100)]
    private ?string $nom = null;

    #[ORM\Column(length: 100)]
    private ?string $prenom = null;

    #[ORM\Column]
    private ?bool $isSystem = false;

    /**
     * @var Collection<int, Possession>
     */
    #[ORM\OneToMany(targetEntity: Possession::class, mappedBy: 'proprietaire', cascade: ['persist'])]
    private Collection $possessions;

    /**
     * @var Collection<int, Cotisation>
     */
    #[ORM\OneToMany(targetEntity: Cotisation::class, mappedBy: 'proprietaire')]
    private Collection $cotisations;

    /**
     * @var Collection<int, Garage>
     */
    #[ORM\OneToMany(targetEntity: Garage::class, mappedBy: 'proprietaire')]
    private Collection $garages;

    #[ORM\Column(length: 50, nullable: true)]
    private ?string $phone = null;

    #[ORM\Column(length: 100, nullable: true)]
    private ?string $city = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $onboardingDoneAt = null;

    public function __construct()
    {
        $this->possessions = new ArrayCollection();
        $this->cotisations = new ArrayCollection();
        $this->garages = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): static
    {
        $this->prenom = $prenom;

        return $this;
    }

    /**
     * @return Collection<int, Possession>|Possession[]
     */
    public function getPossessions(): Collection
    {
        return $this->possessions;
    }

    public function addPossession(Possession $possession): static
    {
        if (!$this->possessions->contains($possession)) {
            $this->possessions->add($possession);
            $possession->setProprietaire($this);
        }

        return $this;
    }

    public function removePossession(Possession $possession): static
    {
        if ($this->possessions->removeElement($possession)) {
            // set the owning side to null (unless already changed)
            if ($possession->getProprietaire() === $this) {
                $possession->setProprietaire(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Cotisation>
     */
    public function getCotisations(): Collection
    {
        return $this->cotisations;
    }

    public function addCotisation(Cotisation $cotisation): static
    {
        if (!$this->cotisations->contains($cotisation)) {
            $this->cotisations->add($cotisation);
            $cotisation->setProprietaire($this);
        }

        return $this;
    }

    public function removeCotisation(Cotisation $cotisation): static
    {
        if ($this->cotisations->removeElement($cotisation)) {
            // set the owning side to null (unless already changed)
            if ($cotisation->getProprietaire() === $this) {
                $cotisation->setProprietaire(null);
            }
        }

        return $this;
    }

    public function getAbsoluteName(): string
    {
        return $this->nom . ' ' . $this->prenom;
    }

    public function isSystem(): ?bool
    {
        return $this->isSystem;
    }

    public function setSystem(bool $isSystem): static
    {
        $this->isSystem = $isSystem;

        return $this;
    }

    public function getNumberOfCurrentAppartement(): int
    {
        return $this->possessions
            ->filter(fn (Possession $possession) => !$possession->getLeaveAt())
            ->count();
    }

    /**
     * @return Collection<int, Garage>|Garage[]
     */
    public function getGarages(): Collection
    {
        return $this->garages;
    }

    public function addGarage(Garage $garage): static
    {
        if (!$this->garages->contains($garage)) {
            $this->garages->add($garage);
            $garage->setProprietaire($this);
        }

        return $this;
    }

    public function removeGarage(Garage $garage): static
    {
        if ($this->garages->removeElement($garage)) {
            // set the owning side to null (unless already changed)
            if ($garage->getProprietaire() === $this) {
                $garage->setProprietaire(null);
            }
        }

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(?string $phone): static
    {
        $this->phone = $phone;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(?string $city): static
    {
        $this->city = $city;

        return $this;
    }

    public function getOnboardingDoneAt(): ?\DateTimeImmutable
    {
        return $this->onboardingDoneAt;
    }

    public function setOnboardingDoneAt(?\DateTimeImmutable $onboardingDoneAt): static
    {
        $this->onboardingDoneAt = $onboardingDoneAt;

        return $this;
    }
}

src/Form/OnboardingType.php
<?php

namespace App\Form;

use App\Entity\Possession;
use App\Entity\Proprietaire;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\OptionsResolver\OptionsResolver;

class OnboardingType extends ProprietaireType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        parent::buildForm($builder, $options);

        $builder->remove('possessions');
        $builder->remove('save');

        $data = null;
        if ($options['possession'] instanceof Possession) {
            $data = $options['possession']->getBeginAt();
        }

        $builder->add('beginAt', DateType::class, [
            'widget' => 'single_text',
            'label' => $this->translator->trans('proprietaire.beginAt'),
            'help' => $this->translator->trans('onboarding.beginAt-help'),
            'mapped' => false,
            'data' => $data
        ])->add('save', SubmitType::class, [
            'label' => $this->translator->trans('save'),
            'attr' => [
                'class' => 'btn btn-primary btn-lg float-end',
            ],
        ]);
    }

    public function finishView(FormView $view, FormInterface $form, array $options): void
    {

    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        parent::configureOptions($resolver);

        $resolver->setDefault('possession', null);
    }
}

src/Controller/OnboardingController.php
<?php

namespace App\Controller;

use App\Entity\Syndic;
use App\Form\OnboardingType;
use App\Repository\AppartementRepository;
use App\Repository\BatimentRepository;
use App\Service\SyndicSessionResolver;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

class OnboardingController extends AbstractController
{

    private Syndic $syndic;

    public function __construct(private readonly SyndicSessionResolver $syndicSessionResolver)
    {
        $this->syndic = $this->syndicSessionResolver->getSelectedSyndic();
    }

    #[Route('/onboarding/1', name: 'app_onboarding_step1')]
    public function step1(Request $request): Response
    {
        $referer = $request->headers->get('referer');
        $route = $this->generateUrl('app_onboarding_step1');
        if (str_ends_with($referer, $route)) {
            return $this->redirectToRoute('app_onboarding_step2');
        }
        return $this->render('onboarding/step1.html.twig');
    }

    #[Route('/onboarding/2', name: 'app_onboarding_step2')]
    public function step2(BatimentRepository $batimentRepository): Response
    {
        return $this->render('onboarding/step2.html.twig', [
            'batiments' => $batimentRepository->getSyndicBatiments($this->syndic),
        ]);
    }

    #[Route('/onboarding/3', name: 'app_onboarding_step3')]
    public function step3(Request $request, AppartementRepository $appartementRepository, EntityManagerInterface $manager): Response
    {
        $form = null;
        $param = $request->get('appartement');

        if (empty($param)) {
            return $this->redirectToRoute('app_onboarding_step2');
        }

        $appart = $appartementRepository->find($param);
        if ($appart) {
            $prop = $appart->getLastProprietaire();
            $possession = $appart->getLastPossession();
            $form = $this->createForm(OnboardingType::class, $prop, ['possession' => $possession]);

            $form->handleRequest($request);

            if ($form->isSubmitted() && $form->isValid()) {
                $prop->setOnboardingDoneAt(new \DateTimeImmutable());

                $beginAt = $form->get('beginAt')->getData();
                if ($possession && $beginAt) {
                    $possession->setBeginAt($beginAt);
                }

                $manager->persist($possession);
                $manager->persist($prop);
                $manager->flush();

                return $this->redirectToRoute('app_home');
            }
        }

        return $this->render('onboarding/step3.html.twig', [
            'propForm' => $form,
            'appart' => $appart
        ]);
    }
}

templates/onboarding/step1.html.twig
{% extends 'base.html.twig' %}

{% import '_components/_macros.html.twig' as macros %}

{% block body %}
    <p>{{ 'onboarding.choose-langue'|trans }}</p>
    {{ macros.selectLang("", false) }}
    <div class="mt-4">
        <a href="{{ path('app_onboarding_step2') }}"
           class="btn btn-lg btn-primary d-inline-flex align-items-center gap-4 float-end"
        >
            {{ 'next'|trans }}
            <i class="fa-solid fa-arrow-right-long"></i>
        </a>
    </div>
{% endblock %}

templates/onboarding/step2.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <p>{{ 'onboarding.choose-batiment'|trans }}</p>
    <form action="{{ path('app_onboarding_step3') }}" method="get" >
        <div class="row g-2 mb-3">
            {% for batiment in batiments %}
                <div class="col">
                    <div>
                        <input type="radio"
                               class="btn-check onboarding__batiment"
                               name="batiment"
                               id="batiment-{{ batiment.nom }}"
                               value="{{ batiment.nom }}"
                               data-appartements="{{ batiment.occupedAppartements|json_encode }}"
                        >
                        <label class="btn btn-lg btn-outline-dark w-100"
                               type="button"
                               for="batiment-{{ batiment.nom }}"
                        >
                            {{ batiment.nom }}
                        </label>
                    </div>
                </div>
            {% endfor %}
        </div>

        <div class="mb-4">
            <label class="opacity-0 form-label"
                   id="onboarding-appartement__label"
                   for="onboarding-appartement"
            >
                {{ 'onboarding.choose-your-appartement'|trans }}
            </label>
            <select name="appartement"
                    id="onboarding-appartement"
                    class="form-select-lg"
                    data-select-allow-empty="true"
                    disabled required
            >
            </select>
        </div>

        <div>
            <button class="btn btn-lg btn-primary float-end d-inline-flex align-items-center gap-4"
                    type="submit"
                    disabled
            >
                {{ 'next'|trans }}
                <i class="fa-solid fa-arrow-right-long"></i>
            </button>
        </div>
    </form>
{% endblock %}

templates/onboarding/step3.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <p>
        <a class="btn btn-sm btn-outline-secondary d-inline-flex align-items-center gap-3"
           href="{{ path('app_onboarding_step2') }}"
        >
            <i class="fa-solid fa-arrow-left-long"></i>
            {{ 'return'|trans }}
        </a>
    </p>

    {% if appart %}
        <div class="alert alert-primary">
            {{ 'onboarding.confirm-selection'|trans({'%appart%': '<b>' ~ appart.absoluteName ~ '</b>'})|raw }}
        </div>
    {% endif %}

    <div>
        {% if propForm %}
            {{ form(propForm) }}
        {% endif %}
    </div>
{% endblock %}