src/Entity/Tarif.php
<?php

namespace App\Entity;

use App\Repository\TarifRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TarifRepository::class)]
class Tarif
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?float $tarif = null;

    #[ORM\ManyToOne(inversedBy: 'tarifs')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Syndic $syndic = null;

    /**
     * @var Collection<int, Cotisation>
     */
    #[ORM\OneToMany(targetEntity: Cotisation::class, mappedBy: 'tarif')]
    private Collection $cotisations;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $debutPeriode = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $finPeriode = null;

    // handle the case of before 2022 periode
    private bool $isBeforeDohaPeriode = false;

    public function __construct()
    {
        $this->cotisations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTarif(): ?float
    {
        return $this->tarif;
    }

    public function setTarif(float $tarif): static
    {
        $this->tarif = $tarif;

        return $this;
    }

    public function getSyndic(): ?Syndic
    {
        return $this->syndic;
    }

    public function setSyndic(?Syndic $syndic): static
    {
        $this->syndic = $syndic;

        return $this;
    }

    /**
     * @return Collection<int, Cotisation>
     */
    public function getCotisations(): Collection
    {
        return $this->cotisations;
    }

    public function addCotisation(Cotisation $cotisation): static
    {
        if (!$this->cotisations->contains($cotisation)) {
            $this->cotisations->add($cotisation);
            $cotisation->setTarif($this);
        }

        return $this;
    }

    public function removeCotisation(Cotisation $cotisation): static
    {
        if ($this->cotisations->removeElement($cotisation)) {
            // set the owning side to null (unless already changed)
            if ($cotisation->getTarif() === $this) {
                $cotisation->setTarif(null);
            }
        }

        return $this;
    }

    public function getDebutPeriode(): ?\DateTimeInterface
    {
        return $this->debutPeriode;
    }

    public function setDebutPeriode(\DateTimeInterface $debutPeriode): static
    {
        $this->debutPeriode = $debutPeriode;

        return $this;
    }

    public function getFinPeriode(): ?\DateTimeInterface
    {
        return $this->finPeriode;
    }

    public function setFinPeriode(\DateTimeInterface $finPeriode): static
    {
        $this->finPeriode = $finPeriode;

        return $this;
    }

    public function getPeriodeYear(): string
    {
        return $this->debutPeriode->format('Y') . ' - ' . $this->finPeriode->format('Y');
    }

    public function isBeforeDohaPeriode(): bool
    {
        return $this->isBeforeDohaPeriode;
    }

    public function setBeforeDohaPeriode(bool $beforeDohaPeriode): Tarif
    {
        $this->isBeforeDohaPeriode = $beforeDohaPeriode;
        return $this;
    }

}

templates/_components/_macros.html.twig
{% macro cotisationStatus(item) %}
    {% if item.status == 'paid' %}
        {% set isPartial = (item.partialPayment and item.partialReason is not empty) %}
        {{ include('_components/badge.html.twig', {
            type: 'success',
            tooltip: isPartial ? item.partialReason : null,
            icon:  isPartial ? 'fa-regular fa-circle-question' : null,
            content: 'cotisation.paid'|trans
        }) }}
    {% elseif item.status == 'incomplete' %}
        {{ include('_components/badge.html.twig', {
            type: 'warning',
            content: 'cotisation.incomplete'|trans
        }) }}
    {% elseif item.status == 'overdue' %}
        {{ include('_components/badge.html.twig', {
            type: 'danger',
            content: 'cotisation.overdue'|trans
        }) }}
    {% elseif item.status == 'exempt' %}
        {{ include('_components/badge.html.twig', {
            content: 'cotisation.exempt'|trans
        }) }}
    {% endif %}
{% endmacro %}

{% macro totalArrow() %}
    <i class="fa-solid {% if app.locale == 'ar' %}fa-arrow-left-long{% else %}fa-arrow-right-long{% endif %} mx-1"></i>
{% endmacro %}

{% macro filterMonth(label, startPeriode, endPeriode, monthSelected) %}
<select class="form-select-sm no-search filter-month"
        name="filterMonth"
        data-select-no-search="true"
        data-select-allow-empty="true"
        data-select-label="{{ label }} :&nbsp;"
>
    <option value="" selected>
        {{ 'depense.filter-month-all'|trans }}
    </option>
    {% set currentDate = date(startPeriode|date('Y-m-d')) %}
    {% set endDate = date(endPeriode|date('Y-m-d')) %}

    {% for date in range(0, endDate|date('U') - currentDate|date('U'), 86400 * 31) %}
        {% if currentDate <= endDate %}
            {% set currentMonth = currentDate|date('m') %}
            {% set currentYear = currentDate|date('Y') %}
            {% set currentValue = currentDate|date('Y-m') %}
            <option value="{{ currentValue }}" {% if monthSelected == currentValue %}selected{% endif %}>
                {{ ('month.'~currentMonth)|trans }} {{ currentYear }}
            </option>
            {% set currentDate = date(currentDate|date_modify('+1 month')|date('Y-m-d')) %}
        {% endif %}
    {% endfor %}
    </select>
{% endmacro %}

{% macro selectLang(class, small = true) %}
    <form method="get"
          action="{{ path('app_lang') }}"
          data-bs-theme="light"
          class="change-lang {{ class }}"
    >
        <select class="form-select-{{ small ? 'sm' : 'lg' }}" name="lang"
                data-select-no-search="true"
                data-select-icon="fa-solid fa-language"
        >
            <option value="fr" {% if app.locale == 'fr' %}selected{% endif %}>Français</option>
            <option value="ar" {% if app.locale == 'ar' %}selected{% endif %}>العربية</option>
            <option value="en" {% if app.locale == 'en' %}selected{% endif %}>English</option>
            <option value="es" {% if app.locale == 'es' %}selected{% endif %}>Español</option>
        </select>
    </form>
{% endmacro %}

templates/_components/badge.html.twig
{% set badge_classes = {
    'danger' : 'text-danger-emphasis bg-danger-subtle border-danger-subtle border',
    'success': 'text-success-emphasis bg-success-subtle border-success-subtle border',
    'warning': 'text-warning-emphasis bg-warning-subtle border-warning-subtle border',
    'default': 'text-dark-emphasis bg-secondary-subtle border-dark-subtle border'
} %}

{% set type = type|default('default') %}
{% set badge_class = badge_classes[type] ?? badge_classes['default'] %}

<span class="badge {{ badge_class }}"
    {% if tooltip is defined and tooltip %}
        data-bs-toggle="tooltip"
        data-bs-title="{{ tooltip }}"
    {% endif %}
>
    {{ content|default('') }}
    {% if icon is defined and icon %}
        <i class="{{ icon }}"></i>
    {% endif %}
</span>

templates/_components/filter-periode.html.twig
<select class="form-select-sm no-search"
        name="filterPeriode"
        data-select-no-search="true"
        data-select-label="{{ label|trans }} :&nbsp;"
>
    {% for tarif in tarifs %}
        <option value="{{ tarif.id }}" {% if tarif is same as tarifSelected %}selected{% endif %}>
            {{ tarif.periodeYear }}
        </option>
    {% endfor %}
    {% if syndic.beforeDohaPeriode %}
        <option value="-1" {% if tarifSelected is not null and tarifSelected.beforeDohaPeriode %}selected{% endif %}>
            {{ 'before-2022'|trans }}
        </option>
    {% endif %}
</select>

templates/_components/preuves-modal.html.twig
<div class="modal fade" tabindex="-1">
    <div class="modal-dialog modal-lg modal-fullscreen-md-down modal-dialog-scrollable">
        <div class="modal-content">
            <div class="modal-body px-1 px-sm-3 px-md-4 px-lg-5">
                <div class="d-flex flex-column gap-2">
                    {% for image in preuves %}
                        <img class="img-fluid" src="{{ path('app_serve_image', {'filename': image, 'folder': pathFolder}) }}" alt="{{ image }}">
                    {% endfor %}
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
                    {{ 'close'|trans }}
                </button>
            </div>
        </div>
    </div>
</div>