src/Entity/Proprietaire.php
<?php

namespace App\Entity;

use App\Repository\ProprietaireRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProprietaireRepository::class)]
class Proprietaire
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 100)]
    private ?string $nom = null;

    #[ORM\Column(length: 100)]
    private ?string $prenom = null;

    #[ORM\Column]
    private ?bool $isSystem = false;

    /**
     * @var Collection<int, Possession>
     */
    #[ORM\OneToMany(targetEntity: Possession::class, mappedBy: 'proprietaire', cascade: ['persist'])]
    private Collection $possessions;

    /**
     * @var Collection<int, Cotisation>
     */
    #[ORM\OneToMany(targetEntity: Cotisation::class, mappedBy: 'proprietaire')]
    private Collection $cotisations;

    /**
     * @var Collection<int, Garage>
     */
    #[ORM\OneToMany(targetEntity: Garage::class, mappedBy: 'proprietaire')]
    private Collection $garages;

    #[ORM\Column(length: 50, nullable: true)]
    private ?string $phone = null;

    #[ORM\Column(length: 100, nullable: true)]
    private ?string $city = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $onboardingDoneAt = null;

    public function __construct()
    {
        $this->possessions = new ArrayCollection();
        $this->cotisations = new ArrayCollection();
        $this->garages = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): static
    {
        $this->prenom = $prenom;

        return $this;
    }

    /**
     * @return Collection<int, Possession>|Possession[]
     */
    public function getPossessions(): Collection
    {
        return $this->possessions;
    }

    public function addPossession(Possession $possession): static
    {
        if (!$this->possessions->contains($possession)) {
            $this->possessions->add($possession);
            $possession->setProprietaire($this);
        }

        return $this;
    }

    public function removePossession(Possession $possession): static
    {
        if ($this->possessions->removeElement($possession)) {
            // set the owning side to null (unless already changed)
            if ($possession->getProprietaire() === $this) {
                $possession->setProprietaire(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Cotisation>
     */
    public function getCotisations(): Collection
    {
        return $this->cotisations;
    }

    public function addCotisation(Cotisation $cotisation): static
    {
        if (!$this->cotisations->contains($cotisation)) {
            $this->cotisations->add($cotisation);
            $cotisation->setProprietaire($this);
        }

        return $this;
    }

    public function removeCotisation(Cotisation $cotisation): static
    {
        if ($this->cotisations->removeElement($cotisation)) {
            // set the owning side to null (unless already changed)
            if ($cotisation->getProprietaire() === $this) {
                $cotisation->setProprietaire(null);
            }
        }

        return $this;
    }

    public function getAbsoluteName(): string
    {
        return $this->nom . ' ' . $this->prenom;
    }

    public function isSystem(): ?bool
    {
        return $this->isSystem;
    }

    public function setSystem(bool $isSystem): static
    {
        $this->isSystem = $isSystem;

        return $this;
    }

    public function getNumberOfCurrentAppartement(): int
    {
        return $this->possessions
            ->filter(fn (Possession $possession) => !$possession->getLeaveAt())
            ->count();
    }

    /**
     * @return Collection<int, Garage>|Garage[]
     */
    public function getGarages(): Collection
    {
        return $this->garages;
    }

    public function addGarage(Garage $garage): static
    {
        if (!$this->garages->contains($garage)) {
            $this->garages->add($garage);
            $garage->setProprietaire($this);
        }

        return $this;
    }

    public function removeGarage(Garage $garage): static
    {
        if ($this->garages->removeElement($garage)) {
            // set the owning side to null (unless already changed)
            if ($garage->getProprietaire() === $this) {
                $garage->setProprietaire(null);
            }
        }

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(?string $phone): static
    {
        $this->phone = $phone;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(?string $city): static
    {
        $this->city = $city;

        return $this;
    }

    public function getOnboardingDoneAt(): ?\DateTimeImmutable
    {
        return $this->onboardingDoneAt;
    }

    public function setOnboardingDoneAt(?\DateTimeImmutable $onboardingDoneAt): static
    {
        $this->onboardingDoneAt = $onboardingDoneAt;

        return $this;
    }
}

src/Form/ProprietaireType.php
<?php

namespace App\Form;

use App\Entity\Proprietaire;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TelType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Contracts\Translation\TranslatorInterface;

class ProprietaireType extends AbstractType
{

    public function __construct(protected TranslatorInterface $translator)
    {
    }

    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom', null, [
                'label' => $this->translator->trans('proprietaire.nom'),
                'attr' => ['class' => 'text-uppercase'],
            ])
            ->add('prenom', null, [
                'label' => $this->translator->trans('proprietaire.prenom'),
            ])
            ->add('phone', TelType::class, [
                'required' => false,
                'label' => $this->translator->trans('proprietaire.phone'),
            ])
            ->add('city', null, [
                'required' => false,
                'label' => $this->translator->trans('proprietaire.city'),
                'help' => $this->translator->trans('proprietaire.city-help'),
            ])
            ->add('possessions', CollectionType::class, [
                'label' => $this->translator->trans('proprietaire.appartements'),
                'entry_type' => PossessionType::class,
                'by_reference' => false,
                'allow_add' => true,
                'entry_options' => [
                    'label' => false,
                ]
            ])
            ->add('save', SubmitType::class, [
                'label' => $this->translator->trans('save')
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Proprietaire::class,
        ]);
    }

    public function finishView(FormView $view, FormInterface $form, array $options): void
    {
        foreach ($view->children as $child) {
            if (isset($options['row_attr'])) {
                $child->vars['row_attr']['class'] = ' ';
            }
        }
    }
}

src/Controller/ProprietaireController.php
<?php

namespace App\Controller;

use App\Entity\Possession;
use App\Entity\Proprietaire;
use App\Entity\Syndic;
use App\Form\ProprietaireType;
use App\Repository\ProprietaireRepository;
use App\Service\SyndicSessionResolver;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

class ProprietaireController extends AbstractController
{

    private Syndic $syndic;

    public function __construct(private SyndicSessionResolver $syndicSessionResolver)
    {
        $this->syndic = $this->syndicSessionResolver->getSelectedSyndic();
    }

    #[Route('/proprietaire', name: 'app_proprietaire_list')]
    public function list(ProprietaireRepository $repository): Response
    {
        return $this->render('proprietaire/list.html.twig', [
            'proprietaires' => $repository->getProprietairesList($this->syndic),
        ]);
    }

    #[Route('/proprietaire/detail/{proprietaire}', name: 'app_proprietaire_detail')]
    public function detail(Proprietaire $proprietaire): Response
    {
        return $this->render('proprietaire/modal-detail.html.twig', [
            'proprietaire' => $proprietaire,
        ]);
    }

    #[IsGranted('ROLE_ADMIN')]
    #[Route('/proprietaire/new', name: 'app_proprietaire_new')]
    public function new(Request $request, EntityManagerInterface $manager): Response
    {
        $proprietaire = new Proprietaire();
        $proprietaire->addPossession(new Possession());

        $form = $this->createForm(ProprietaireType::class, $proprietaire);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $manager->persist($proprietaire);
            $manager->flush();

            return $this->redirectToRoute('app_proprietaire_list');
        }

        return $this->render('proprietaire/save.html.twig', [
            'form' => $form,
            'mode' => 'new',
        ]);
    }

    #[IsGranted('ROLE_ADMIN')]
    #[Route('/proprietaire/edit/{proprietaire}', name: 'app_proprietaire_edit')]
    public function edit(Proprietaire $proprietaire, Request $request, EntityManagerInterface $manager): Response
    {
        $form = $this->createForm(ProprietaireType::class, $proprietaire);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $manager->flush();

            return $this->redirectToRoute('app_proprietaire_list');
        }

        return $this->render('proprietaire/save.html.twig', [
            'form' => $form,
            'mode' => 'edit',
        ]);
    }
}

templates/proprietaire/_display-name.html.twig
{% if proprietaire is null %}
    -
{% elseif is_granted('ROLE_ADMIN') and proprietaire.isSystem == false  %}
    <span class="link-primary link-opacity-75-hover cursor-pointer"
          data-url="{{ path('app_proprietaire_detail', {'proprietaire': proprietaire.id}) }}"
    >
        {{ proprietaire.absoluteName }}
    </span>
{% else %}
    {{ proprietaire.absoluteName }}
{% endif %}

templates/proprietaire/_display-phone.html.twig
{% if proprietaire.phone is not empty %}
    <a href="tel:{{ proprietaire.phone }}">{{ proprietaire.phone }}</a>
{% else %}
    -
{% endif %}

templates/proprietaire/list.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    {{ 'proprietaire.list'|trans }}
{% endblock %}

{% block body %}
    <div class="d-flex align-items-center flex-wrap">
        <h2 class="flex-fill">{{ 'proprietaire.list'|trans }}</h2>
        <a href="{{ path('app_proprietaire_new') }}" class="btn btn-primary" >{{ 'proprietaire.new'|trans }}</a>
    </div>
    <div class="table-responsive">
        <table class="table table-sm table-striped table-hover">
            <thead class="thead-dark">
            <tr>
                <th></th>
                <th scope="col">{{ 'appartement.nom'|trans }}</th>
                <th scope="col">{{ 'proprietaire.nom'|trans }}</th>
                <th scope="col">{{ 'proprietaire.prenom'|trans }}</th>
                <th scope="col">{{ 'proprietaire.phone'|trans }}</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            {% for proprietaire in proprietaires %}
                <tr {% if proprietaire.system == false %}data-url="{{ path('app_proprietaire_detail', {'proprietaire': proprietaire.id}) }}"{% endif %}>
                    <td style="width: 1px">
                        {% if proprietaire.system == false %}
                            <button class="btn-sm btn btn-light">
                                <i class="fa-solid fa-folder-open"></i>
                            </button>
                        {% endif%}
                    </td>
                    <td>
                        {% if proprietaire.system %}
                            {{ include('_components/badge.html.twig', {
                                content: 'appartement.count'|trans({'%count%': proprietaire.numberOfCurrentAppartement})
                            }) }}
                        {% elseif proprietaire.numberOfCurrentAppartement == 0 %}
                            {{ include('_components/badge.html.twig', {
                                content: 'appartement.empty'|trans
                            }) }}
                        {% else %}
                            {% for possession in proprietaire.possessions %}
                                {% if possession.leaveAt is null %}
                                    <div class="d-flex gap-2 align-items-center">
                                    <span style="min-width: 36px">
                                        {{ possession.appartement.absoluteName(false) }}
                                    </span>
                                        {{ include('_components/badge.html.twig', {
                                            content: 'from'|trans({'%from%': (possession.beginAt|date)})
                                        }) }}
                                    </div>
                                {% endif %}
                            {% endfor %}
                        {% endif %}
                    </td>
                    <td>{{ proprietaire.nom }}</td>
                    <td>{{ proprietaire.prenom }}</td>
                    <td>
                        {% include 'proprietaire/_display-phone.html.twig' %}
                    </td>
                    <td>
                        <a href="{{ path('app_proprietaire_edit', {'proprietaire': proprietaire.id}) }}">
                            {{ 'edit'|trans }}
                        </a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

templates/proprietaire/modal-detail.html.twig
<div class="modal fade" tabindex="-1">
    <div class="modal-dialog modal-fullscreen-sm-down">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">{{ 'proprietaire.detail'|trans }}</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body p-0">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">
                        <b>{{ 'proprietaire.nom'|trans }}:</b> {{ proprietaire.nom }}
                    </li>
                    <li class="list-group-item">
                        <b>{{ 'proprietaire.prenom'|trans }}:</b> {{ proprietaire.prenom }}
                    </li>
                    {% if is_granted('ROLE_ADMIN') %}
                        <li class="list-group-item">
                            <b>{{ 'proprietaire.phone'|trans }}:</b> {% include 'proprietaire/_display-phone.html.twig' %}
                        </li>
                        <li class="list-group-item">
                            <b>{{ 'proprietaire.city'|trans }}:</b> {{ proprietaire.city }}
                        </li>
                    {% endif %}
                    {% for possession in proprietaire.possessions %}
                        <li class="list-group-item">
                            <b>{{ 'appartement.nom'|trans }}:</b> {{ possession.appartement.absoluteName }}
                        </li>
                        <li class="list-group-item">
                            <b>{{ 'proprietaire.beginAt'|trans }}:</b> {{ possession.beginAt|date }}
                        </li>
                    {% endfor %}
                    {% for garage in proprietaire.garages %}
                        <li class="list-group-item d-flex gap-2 align-items-center">
                            <b>{{ 'garage.nav'|trans }}:</b> {{ garage.nom }}
                            {{ include('_components/badge.html.twig', {
                                content: ('garage.dateAchat'|trans) ~ ': ' ~ (garage.dateAchat|date)
                            }) }}
                        </li>
                    {% endfor %}
                </ul>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
                    {{ 'close'|trans }}
                </button>
            </div>
        </div>
    </div>
</div>

templates/proprietaire/save.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    {{ ('proprietaire.' ~ mode)|trans }}
{% endblock %}

{% block body %}
    <h2>{{ ('proprietaire.' ~ mode)|trans }}</h2>
    {{ form_start(form) }}
        <div class="row g-2 g-md-3 mb-3">
            <div class="col-md-6">
                {{ form_row(form.nom) }}
            </div>
            <div class="col-md-6">
                {{ form_row(form.prenom) }}
            </div>
        </div>

        <div class="row g-2 g-md-3 mb-2 mb-md-0">
            <div class="col-md-6">
                {{ form_row(form.phone) }}
            </div>
            <div class="col-md-6">
                {{ form_row(form.city) }}
            </div>
        </div>

        {{ form_row(form.possessions) }}
        <div class="text-end">
            <button class="btn btn-link p-0" type="button" id="addAppartement">
                {{ 'proprietaire.appartements-add'|trans }}
            </button>
        </div>
        {{ form_rest(form) }}
    {{ form_end(form) }}
{% endblock %}